### ISSUE TITLE
ISS electrometer tasks

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-ISS/profile_collection#38]
Based on the PR #37.

## TODOs
- [x] ~set the values on the `stage`~:
  - `FA Divide` (currently set to `370` for testing)
  - `Stream Samples` (currently set to `500_000` for testing)
- [x] remove the `FAstream.bin` and `FAstreamSettings.txt` files from previous run (currently the name is not configurable) on the IOC before/after the scan
- [x] ~figure out what is `37.0` in~ https://github.com/NSLS-II-ISS/profile_collection/blob/4bc3151a358b5c8e71e8f519fceb0bc34b3c98a9/startup/scripts/future-handler/binaryRead.py#L36-L39
  Answer: it's the `FA Divide` field's value.

- [ ] configurable number of pizza-boxes
- [x] add metadata to the scan

## Screenshots
![electrometer](https://user-images.githubusercontent.com/13209176/64365839-f450b800-cfe2-11e9-8c43-5066242a1fba.png)

**Comment by mrakitin** [comment]
Implemented in 2020, ready for production.
